In [2]:
#Dave's code

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time #Included to use in pausing between API requests
import re  #Enable regular expressions

# Import API key
from api_keys import api_key

In [47]:
#Dave's code

#Make API calls to US Census Bureau - American Community Survey 1-Year Data
#https://www.census.gov/data/developers/data-sets/acs-1year.2017.html
#Data will be returned on a county & state basis

#Set the range of years to pull from the api
years = ["2012","2013","2014","2015","2016","2017"]

#List of fields to request from the API
#Would like to build this into a file, with columns for the ID required for the API call and a human readable name for output
fields = ["NAME","S0101_C01_001E","S1701_C01_001E","S1701_C02_001E","S1702_C01_001E","S1702_C02_001E",
          "S1703_C01_001E","S1703_C02_001E"]

#Initiate an empty list to hold census records
census_data_raw = []

#Turn the list of fields into a string to use in the api url
field_list = ','.join(fields)

#Base url for the API request. YEAR and FIELDS are placeholders and will be substituted with values
#Using * for county and state will pull all available records
census_base_url = "https://api.census.gov/data/YEAR/acs/acs1/subject?get=FIELDS&for=county:*&in=state:*&key="

#Since API url has a year component, loop through the list of years to pull back the relevant data
for year in years:
    census_url = re.sub("YEAR", year, census_base_url) #Use regular expression to substitute the year into the base url
    census_url = re.sub("FIELDS", field_list, census_url) #Use regular expression to substitute in list of fields
    #print(census_url) #for debugging
    response = requests.get(census_url + api_key).json()
    #print(response) #for debugging
    for census_record in response[1:]: #Ignore first record in the loop
        census_record.append(year)  #Append the year to the end of the returned record
        census_data_raw.append(census_record)  #Append the full record to the list of records
    time.sleep(1) #Sleep for a second, because APIs

#census_data_raw #for debugging

In [2]:
#Dave's code

#Set path for output file
output_data_file = "census_data\census_data.tsv"

#Use the list of fields as the headers for the data frame
headers = fields 
#Add titles for fields returned in API that aren't part of requested fields
headers.extend(["STATE","COUNTY","YEAR"])

#Convert list of census data to a dataframe
census_data_raw_df = pd.DataFrame(census_data_raw, columns=headers)

#Export dataframe to a tab-delimited file, since one of the columns includes a comma
census_data_raw_df.to_csv(output_data_file, sep="\t", index=False, encoding='utf-8')

#show the dataframe
census_data_raw_df

NameError: name 'fields' is not defined

In [ ]:
#Doug's code

In [ ]:
#Scott's code

In [ ]:
#Megan's code

In [ ]:
#Justin's code

In [3]:
#Justin's code
#Call this function again so I don't have to run that giant API call in Dave's code
output_data_file = "census_data\census_data.tsv"

#read in the file and save it to a df
justin_df = pd.read_csv(output_data_file, sep="\t", encoding='utf-8')

#rename columns to the best of my ability
justin_df.columns = ['Name', 'Total Population', 'Poverty Determinable', 'Below Poverty Level (PL)', 'Poverty Status of Families',
                     '% of Families Below PL', 'Selected Characteristics', '<50% Poverty Level', 'State Code', 'County Code', "Year"]

#calculate a new value to eventually add to our dataframe as a column
percent_below_PL = justin_df['Below Poverty Level (PL)'] / justin_df['Poverty Determinable']

#format this value to be the same as the other percentage fetched from the API
percent_below_PL_formatted = []
for value in percent_below_PL:
    value = value * 100
    value = "{:.1f}".format(value)
    percent_below_PL_formatted.append(value)
    
#add this new value as a column to our df
justin_df['% Below PL'] = percent_below_PL_formatted

#move this column to a more sensible position
justin_cols = list(justin_df)
justin_cols.insert(4, justin_cols.pop(justin_cols.index('% Below PL')))
justin_df = justin_df.loc[:, justin_cols]

#show new and sexy dataframe
justin_df

,Name,Total Population,Poverty Determinable,Below Poverty Level (PL),% Below PL,Poverty Status of Families,% of Families Below PL,Selected Characteristics,<50% Poverty Level,State Code,County Code,Year
0,"Ouachita Parish, Louisiana",155363,146095,35443,24.3,37910,20.0,NaN,NaN,22,73,2012
1,"Rapides Parish, Louisiana",132373,128128,28867,22.5,33286,17.2,NaN,NaN,22,79,2012
2,"St. Landry Parish, Louisiana",83662,82325,21149,25.7,21943,21.0,NaN,NaN,22,97,2012
3,"St. Tammany Parish, Louisiana",239453,237342,32212,13.6,65316,10.2,NaN,NaN,22,103,2012
4,"Tangipahoa Parish, Louisiana",123441,119480,29110,24.4,27469,18.9,NaN,NaN,22,105,2012
5,"Terrebonne Parish, Louisiana",111893,110088,20330,18.5,27860,12.7,NaN,NaN,22,109,2012
6,"Androscoggin County, Maine",107609,104067,16593,15.9,27924,12.1,NaN,NaN,23,1,2012
7,"Aroostook County, Maine",70868,68715,11358,16.5,20883,11.9,NaN,NaN,23,3,2012
8,"Cumberland County, Maine",283921,275849,32297,11.7,71533,8.2,NaN,NaN,23,5,2012
9,"Kennebec County, Maine",121853,118408,17804,15.0,31164,9.5,NaN,NaN,23,11,2012
10,"Penobscot County, Maine",153746,146973,26664,18.1,37996,11.4,NaN,NaN,23,19,2012
11,"York County, Maine",199005,195998,22771,11.6,52004,7.0,NaN,NaN,23,31,2012
12,"Allegany County, Maryland",74012,66749,11401,17.1,16192,10.8,NaN,NaN,24,1,2012
13,"Anne Arundel County, Maryland",550488,534476,30494,5.7,142389,3.5,NaN,NaN,24,3,2012
14,"Baltimore County, Maryland",817455,796529,76903,9.7,199190,6.2,796529.0,5.2,24,5,2012
15,"Calvert County, Maryland",89628,89011,6451,7.2,23092,4.3,NaN,NaN,24,9,2012
16,"Carroll County, Maryland",167217,163721,10179,6.2,42565,3.5,NaN,NaN,24,13,2012
17,"Cecil County, Maryland",101696,100191,14438,14.4,24563,9.6,NaN,NaN,24,15,2012
18,"Charles County, Maryland",150592,149267,14439,9.7,37523,7.2,NaN,NaN,24,17,2012
19,"Frederick County, Maryland",239582,235236,15942,6.8,62954,5.1,NaN,NaN,24,21,2012
20,"Harford County, Maryland",248622,245875,20312,8.3,66001,6.3,NaN,NaN,24,25,2012
21,"Howard County, Maryland",299430,298129,13487,4.5,82343,3.4,NaN,NaN,24,27,2012
22,"Montgomery County, Maryland",1004709,996632,64037,6.4,250105,4.3,996632.0,2.7,24,31,2012
23,"Prince George's County, Maryland",881138,860321,88114,10.2,196913,7.3,860321.0,4.8,24,33,2012
24,"St. Mary's County, Maryland",108987,106281,7483,7.0,29743,5.2,NaN,NaN,24,37,2012
25,"Washington County, Maryland",149180,140388,19908,14.2,39079,11.5,NaN,NaN,24,43,2012
26,"Wicomico County, Maryland",100647,96618,15810,16.4,25545,12.1,NaN,NaN,24,45,2012
27,"Baltimore city, Maryland",621342,598255,148491,24.8,123565,21.4,598255.0,11.7,24,510,2012
28,"Barnstable County, Massachusetts",215423,212878,21947,10.3,56740,6.1,NaN,NaN,25,1,2012
29,"Berkshire County, Massachusetts",130016,124178,17437,14.0,32770,10.8,NaN,NaN,25,3,2012
...,...,...,...,...,...,...,...,...,...,...,...,...
4949,"Kenosha County, Wisconsin",168521,163934,18698,11.4,41414,7.8,NaN,NaN,55,59,2017
4950,"La Crosse County, Wisconsin",118274,113369,13961,12.3,28125,4.4,NaN,NaN,55,63,2017
4951,"Manitowoc County, Wisconsin",79175,78401,6937,8.8,21888,6.2,NaN,NaN,55,71,2017
4952,"Marathon County, Wisconsin",135732,133484,13885,10.4,35549,6.4,NaN,NaN,55,73,2017
4953,"Milwaukee County, Wisconsin",952085,929532,175772,18.9,207474,14.1,929532.0,8.2,55,79,2017
4954,"Outagamie County, Wisconsin",186059,182448,12863,7.1,49467,5.4,NaN,NaN,55,87,2017
4955,"Ozaukee County, Wisconsin",88429,86478,4790,5.5,24772,3.0,NaN,NaN,55,89,2017
4956,"Portage County, Wisconsin",70474,67142,8786,13.1,16569,5.5,NaN,NaN,55,97,2017
4957,"Racine County, Wisconsin",196071,190946,19579,10.3,52537,7.1,NaN,NaN,55,101,2017
4958,"Rock County, Wisconsin",162309,159259,19945,12.5,42556,8.8,NaN,NaN,55,105,2017
4959,"St. Croix County, Wisconsin",88703,87565,3095,3.5,24997,1.6,NaN,NaN,55,109,2017
4960,"Sheboygan County, Wisconsin",115344,112332,8110,7.2,31311,4.3,NaN,NaN,55,117,2017
4961,"Walworth County, Wisconsin",103082,100075,10609,10.6,27300,5.3,NaN,NaN,55,127,2017
4962,"Washington County, Wisconsin",135101,134241,6644,4.9,37860,2.6,NaN,NaN,55,131,2017
4963,"Waukesha County, Wisconsin",400621,395240,18842,4.8,110972,3.1,NaN,NaN,55,133,2017
4964,"Winnebago County, Wisconsin",170414,162831,19686,12.1,42046,6.7,NaN,NaN,55,139,2017
4965,"Wood County, Wisconsin",73126,72049,7775,10.8,20358,8.5,NaN,NaN,55,141,2017
4966,"Laramie County, Wyoming",98327,96346,9563,9.9,25549,6.7,NaN,NaN,56,21,2017
4967,"Natrona County, Wyoming",79547,77303,8418,10.9,20598,6.4,NaN,NaN,56,25,2017
4968,"Arecibo Municipio, Puerto Rico",86066,85319,41275,48.4,22637,44.2,NaN,NaN,72,13,2017
4969,"Bayam?n Municipio, Puerto Rico",179565,173218,58560,33.8,44016,32.1,NaN,NaN,72,21,2017
4970,"Caguas Municipio, Puerto Rico",129604,129400,53049,41.0,30209,36.6,NaN,NaN,72,25,2017
4971,"Carolina Municipio, Puerto Rico",154489,153736,40140,26.1,41275,24.0,NaN,NaN,72,31,2017
4972,"Guaynabo Municipio, Puerto Rico",87328,87077,24144,27.7,15173,23.4,NaN,NaN,72,61,2017
4973,"Mayag?ez Municipio, Puerto Rico",75525,74407,37015,49.7,18212,45.3,NaN,NaN,72,97,2017
4974,"Ponce Municipio, Puerto Rico",140859,136612,72708,53.2,33983,49.4,NaN,NaN,72,113,2017
4975,"San Juan Municipio, Puerto Rico",337288,332876,132263,39.7,78242,36.1,NaN,NaN,72,127,2017
4976,"Toa Alta Municipio, Puerto Rico",73217,73129,22225,30.4,16013,30.4,NaN,NaN,72,135,2017
4977,"Toa Baja Municipio, Puerto Rico",78092,78034,26276,33.7,18940,28.6,NaN,NaN,72,137,2017
4978,"Trujillo Alto Municipio, Puerto Rico",66675,66453,18426,27.7,17455,24.6,NaN,NaN,72,139,2017

In [47]:
# Loading EPA data

import os

def read_all_epa_years ():
    
    # Base file name
    base_name = "annual_aqi_by_county_"
    # epa_data_directory
    data_directory = "epa_data"
    
    years = [2012, 2013, 2014, 2015, 2016, 2017]
    df_list = []
    
    # Loop over the years, read in .csv file and append to list of dataframes
    for year in years:
        file_name = f"{base_name}{year}.csv"
        file_path = os.path.join("", data_directory, file_name)
        
        df_list.append(pd.read_csv(file_path))
    
    # concatenate the years
    all_years_df = pd.concat(df_list, ignore_index=True)
    
    # write the combined dataframe to a new .csv file
    output_path = os.path.join("", data_directory, "annual_aqi_by_county_all.csv")
    all_years_df.to_csv(output_path)
    
    # return the dataframe
    return all_years_df

all_years_df = read_all_epa_years()

In [48]:
all_years_df.shape

(6363, 19)

In [49]:
all_years_df.columns

Index(['State', 'County', 'Year', 'Days with AQI', 'Good Days',
       'Moderate Days', 'Unhealthy for Sensitive Groups Days',
       'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI',
       '90th Percentile AQI', 'Median AQI', 'Days CO', 'Days NO2',
       'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10'],
      dtype='object')

In [50]:
all_years_df['State'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Country Of Mexico', 'Delaware',
       'District Of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
       'Virgin Islands', 'Virginia', 'Washington', 'West Virginia',
       'Wisconsin', 'Wyoming'], dtype=object)

In [51]:
justin_df.columns

Index(['Name', 'Total Population', 'Poverty Determinable',
       'Below Poverty Level (PL)', '% Below PL', 'Poverty Status of Families',
       '% of Families Below PL', 'Selected Characteristics',
       '<50% Poverty Level', 'State Code', 'County Code', 'Year'],
      dtype='object')

In [57]:
sum(justin_df.Name.str.contains("Puerto Rico"))

66

In [58]:
sum(justin_df.Name.str.contains("District of Columbia"))

6

In [55]:
(justin_df.Name.str.contains("Virgin Islands"))

4979

In [56]:
len(justin_df.Name.str.contains("Country of Mexico"))

4979