In [2]:
#Dave's code

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time #Included to use in pausing between API requests
import re  #Enable regular expressions

# Import API key
from api_keys import api_key

In [47]:
#Dave's code

#Make API calls to US Census Bureau - American Community Survey 1-Year Data
#https://www.census.gov/data/developers/data-sets/acs-1year.2017.html
#Data will be returned on a county & state basis

#Set the range of years to pull from the api
years = ["2012","2013","2014","2015","2016","2017"]

#List of fields to request from the API
#Would like to build this into a file, with columns for the ID required for the API call and a human readable name for output
fields = ["NAME","S0101_C01_001E","S1701_C01_001E","S1701_C02_001E","S1702_C01_001E","S1702_C02_001E",
          "S1703_C01_001E","S1703_C02_001E"]

#Initiate an empty list to hold census records
census_data_raw = []

#Turn the list of fields into a string to use in the api url
field_list = ','.join(fields)

#Base url for the API request. YEAR and FIELDS are placeholders and will be substituted with values
#Using * for county and state will pull all available records
census_base_url = "https://api.census.gov/data/YEAR/acs/acs1/subject?get=FIELDS&for=county:*&in=state:*&key="

#Since API url has a year component, loop through the list of years to pull back the relevant data
for year in years:
    census_url = re.sub("YEAR", year, census_base_url) #Use regular expression to substitute the year into the base url
    census_url = re.sub("FIELDS", field_list, census_url) #Use regular expression to substitute in list of fields
    #print(census_url) #for debugging
    response = requests.get(census_url + api_key).json()
    #print(response) #for debugging
    for census_record in response[1:]: #Ignore first record in the loop
        census_record.append(year)  #Append the year to the end of the returned record
        census_data_raw.append(census_record)  #Append the full record to the list of records
    time.sleep(1) #Sleep for a second, because APIs

#census_data_raw #for debugging

In [2]:
#Dave's code

#Set path for output file
output_data_file = "census_data\census_data.tsv"

#Use the list of fields as the headers for the data frame
headers = fields 
#Add titles for fields returned in API that aren't part of requested fields
headers.extend(["STATE","COUNTY","YEAR"])

#Convert list of census data to a dataframe
census_data_raw_df = pd.DataFrame(census_data_raw, columns=headers)

#Export dataframe to a tab-delimited file, since one of the columns includes a comma
census_data_raw_df.to_csv(output_data_file, sep="\t", index=False, encoding='utf-8')

#show the dataframe
census_data_raw_df

NameError: name 'fields' is not defined

In [ ]:
#Doug's code

In [ ]:
#Scott's code

In [ ]:
#Megan's code

In [ ]:
#Justin's code

In [3]:
#Justin's code
#Call this function again so I don't have to run that giant API call in Dave's code
output_data_file = "census_data\census_data.tsv"

#read in the file and save it to a df
justin_df = pd.read_csv(output_data_file, sep="\t", encoding='utf-8')

#rename columns to the best of my ability
justin_df.columns = ['Name', 'Total Population', 'Poverty Determinable', 'Below Poverty Level (PL)', 'Poverty Status of Families',
                     '% of Families Below PL', 'Selected Characteristics', '<50% Poverty Level', 'State Code', 'County Code', "Year"]

#calculate a new value to eventually add to our dataframe as a column
percent_below_PL = justin_df['Below Poverty Level (PL)'] / justin_df['Poverty Determinable']

#format this value to be the same as the other percentage fetched from the API
percent_below_PL_formatted = []
for value in percent_below_PL:
    value = value * 100
    value = "{:.1f}".format(value)
    percent_below_PL_formatted.append(value)
    
#add this new value as a column to our df
justin_df['% Below PL'] = percent_below_PL_formatted

#move this column to a more sensible position
justin_cols = list(justin_df)
justin_cols.insert(4, justin_cols.pop(justin_cols.index('% Below PL')))
justin_df = justin_df.loc[:, justin_cols]

#show new and sexy dataframe
justin_df

,Name,Total Population,Poverty Determinable,Below Poverty Level (PL),% Below PL,Poverty Status of Families,% of Families Below PL,Selected Characteristics,<50% Poverty Level,State Code,County Code,Year
0,"Ouachita Parish, Louisiana",155363,146095,35443,24.3,37910,20.0,NaN,NaN,22,73,2012
1,"Rapides Parish, Louisiana",132373,128128,28867,22.5,33286,17.2,NaN,NaN,22,79,2012
2,"St. Landry Parish, Louisiana",83662,82325,21149,25.7,21943,21.0,NaN,NaN,22,97,2012
3,"St. Tammany Parish, Louisiana",239453,237342,32212,13.6,65316,10.2,NaN,NaN,22,103,2012
4,"Tangipahoa Parish, Louisiana",123441,119480,29110,24.4,27469,18.9,NaN,NaN,22,105,2012
5,"Terrebonne Parish, Louisiana",111893,110088,20330,18.5,27860,12.7,NaN,NaN,22,109,2012
6,"Androscoggin County, Maine",107609,104067,16593,15.9,27924,12.1,NaN,NaN,23,1,2012
7,"Aroostook County, Maine",70868,68715,11358,16.5,20883,11.9,NaN,NaN,23,3,2012
8,"Cumberland County, Maine",283921,275849,32297,11.7,71533,8.2,NaN,NaN,23,5,2012
9,"Kennebec County, Maine",121853,118408,17804,15.0,31164,9.5,NaN,NaN,23,11,2012
10,"Penobscot County, Maine",153746,146973,26664,18.1,37996,11.4,NaN,NaN,23,19,2012
11,"York County, Maine",199005,195998,22771,11.6,52004,7.0,NaN,NaN,23,31,2012
12,"Allegany County, Maryland",74012,66749,11401,17.1,16192,10.8,NaN,NaN,24,1,2012
13,"Anne Arundel County, Maryland",550488,534476,30494,5.7,142389,3.5,NaN,NaN,24,3,2012
14,"Baltimore County, Maryland",817455,796529,76903,9.7,199190,6.2,796529.0,5.2,24,5,2012
15,"Calvert County, Maryland",89628,89011,6451,7.2,23092,4.3,NaN,NaN,24,9,2012
16,"Carroll County, Maryland",167217,163721,10179,6.2,42565,3.5,NaN,NaN,24,13,2012
17,"Cecil County, Maryland",101696,100191,14438,14.4,24563,9.6,NaN,NaN,24,15,2012
18,"Charles County, Maryland",150592,149267,14439,9.7,37523,7.2,NaN,NaN,24,17,2012
19,"Frederick County, Maryland",239582,235236,15942,6.8,62954,5.1,NaN,NaN,24,21,2012
20,"Harford County, Maryland",248622,245875,20312,8.3,66001,6.3,NaN,NaN,24,25,2012
21,"Howard County, Maryland",299430,298129,13487,4.5,82343,3.4,NaN,NaN,24,27,2012
22,"Montgomery County, Maryland",1004709,996632,64037,6.4,250105,4.3,996632.0,2.7,24,31,2012
23,"Prince George's County, Maryland",881138,860321,88114,10.2,196913,7.3,860321.0,4.8,24,33,2012
24,"St. Mary's County, Maryland",108987,106281,7483,7.0,29743,5.2,NaN,NaN,24,37,2012
25,"Washington County, Maryland",149180,140388,19908,14.2,39079,11.5,NaN,NaN,24,43,2012
26,"Wicomico County, Maryland",100647,96618,15810,16.4,25545,12.1,NaN,NaN,24,45,2012
27,"Baltimore city, Maryland",621342,598255,148491,24.8,123565,21.4,598255.0,11.7,24,510,2012
28,"Barnstable County, Massachusetts",215423,212878,21947,10.3,56740,6.1,NaN,NaN,25,1,2012
29,"Berkshire County, Massachusetts",130016,124178,17437,14.0,32770,10.8,NaN,NaN,25,3,2012
...,...,...,...,...,...,...,...,...,...,...,...,...
4949,"Kenosha County, Wisconsin",168521,163934,18698,11.4,41414,7.8,NaN,NaN,55,59,2017
4950,"La Crosse County, Wisconsin",118274,113369,13961,12.3,28125,4.4,NaN,NaN,55,63,2017
4951,"Manitowoc County, Wisconsin",79175,78401,6937,8.8,21888,6.2,NaN,NaN,55,71,2017
4952,"Marathon County, Wisconsin",135732,133484,13885,10.4,35549,6.4,NaN,NaN,55,73,2017
4953,"Milwaukee County, Wisconsin",952085,929532,175772,18.9,207474,14.1,929532.0,8.2,55,79,2017
4954,"Outagamie County, Wisconsin",186059,182448,12863,7.1,49467,5.4,NaN,NaN,55,87,2017
4955,"Ozaukee County, Wisconsin",88429,86478,4790,5.5,24772,3.0,NaN,NaN,55,89,2017
4956,"Portage County, Wisconsin",70474,67142,8786,13.1,16569,5.5,NaN,NaN,55,97,2017
4957,"Racine County, Wisconsin",196071,190946,19579,10.3,52537,7.1,NaN,NaN,55,101,2017
4958,"Rock County, Wisconsin",162309,159259,19945,12.5,42556,8.8,NaN,NaN,55,105,2017
4959,"St. Croix County, Wisconsin",88703,87565,3095,3.5,24997,1.6,NaN,NaN,55,109,2017
4960,"Sheboygan County, Wisconsin",115344,112332,8110,7.2,31311,4.3,NaN,NaN,55,117,2017
4961,"Walworth County, Wisconsin",103082,100075,10609,10.6,27300,5.3,NaN,NaN,55,127,2017
4962,"Washington County, Wisconsin",135101,134241,6644,4.9,37860,2.6,NaN,NaN,55,131,2017
4963,"Waukesha County, Wisconsin",400621,395240,18842,4.8,110972,3.1,NaN,NaN,55,133,2017
4964,"Winnebago County, Wisconsin",170414,162831,19686,12.1,42046,6.7,NaN,NaN,55,139,2017
4965,"Wood County, Wisconsin",73126,72049,7775,10.8,20358,8.5,NaN,NaN,55,141,2017
4966,"Laramie County, Wyoming",98327,96346,9563,9.9,25549,6.7,NaN,NaN,56,21,2017
4967,"Natrona County, Wyoming",79547,77303,8418,10.9,20598,6.4,NaN,NaN,56,25,2017
4968,"Arecibo Municipio, Puerto Rico",86066,85319,41275,48.4,22637,44.2,NaN,NaN,72,13,2017
4969,"Bayam?n Municipio, Puerto Rico",179565,173218,58560,33.8,44016,32.1,NaN,NaN,72,21,2017
4970,"Caguas Municipio, Puerto Rico",129604,129400,53049,41.0,30209,36.6,NaN,NaN,72,25,2017
4971,"Carolina Municipio, Puerto Rico",154489,153736,40140,26.1,41275,24.0,NaN,NaN,72,31,2017
4972,"Guaynabo Municipio, Puerto Rico",87328,87077,24144,27.7,15173,23.4,NaN,NaN,72,61,2017
4973,"Mayag?ez Municipio, Puerto Rico",75525,74407,37015,49.7,18212,45.3,NaN,NaN,72,97,2017
4974,"Ponce Municipio, Puerto Rico",140859,136612,72708,53.2,33983,49.4,NaN,NaN,72,113,2017
4975,"San Juan Municipio, Puerto Rico",337288,332876,132263,39.7,78242,36.1,NaN,NaN,72,127,2017
4976,"Toa Alta Municipio, Puerto Rico",73217,73129,22225,30.4,16013,30.4,NaN,NaN,72,135,2017
4977,"Toa Baja Municipio, Puerto Rico",78092,78034,26276,33.7,18940,28.6,NaN,NaN,72,137,2017
4978,"Trujillo Alto Municipio, Puerto Rico",66675,66453,18426,27.7,17455,24.6,NaN,NaN,72,139,2017

In [4]:
justin_df.head()

,Name,Total Population,Poverty Determinable,Below Poverty Level (PL),% Below PL,Poverty Status of Families,% of Families Below PL,Selected Characteristics,<50% Poverty Level,State Code,County Code,Year
0,"Ouachita Parish, Louisiana",155363,146095,35443,24.3,37910,20.0,NaN,NaN,22,73,2012
1,"Rapides Parish, Louisiana",132373,128128,28867,22.5,33286,17.2,NaN,NaN,22,79,2012
2,"St. Landry Parish, Louisiana",83662,82325,21149,25.7,21943,21.0,NaN,NaN,22,97,2012
3,"St. Tammany Parish, Louisiana",239453,237342,32212,13.6,65316,10.2,NaN,NaN,22,103,2012
4,"Tangipahoa Parish, Louisiana",123441,119480,29110,24.4,27469,18.9,NaN,NaN,22,105,2012

In [6]:
justin_df['Year'].nunique()

6

In [7]:
justin_df['Year'].unique()

array([2012, 2013, 2014, 2015, 2016, 2017], dtype=int64)

In [8]:
justin_df.shape

(4979, 12)

In [9]:
justin_df['Name'].nunique()

841

In [10]:
aqi_2012_df = pd.read_csv('Copy of annual_aqi_by_county_2012.csv')

In [11]:
aqi_2012_df.shape

(1071, 19)

In [12]:
aqi_2012_df.head()

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,Baldwin,2012,284,226,56,2,0,0,0,112,61,38,0,0,210,0,74,0
1,Alabama,Clay,2012,121,99,22,0,0,0,0,72,56,35,0,0,0,0,121,0
2,Alabama,Colbert,2012,283,222,55,6,0,0,0,136,62,40,0,0,209,0,74,0
3,Alabama,DeKalb,2012,361,282,74,5,0,0,0,115,64,40,0,0,320,0,41,0
4,Alabama,Elmore,2012,245,212,33,0,0,0,0,100,54,40,0,0,245,0,0,0

In [20]:
aqi_2012_df.loc[aqi_2012_df['State'] == 'Louisiana']

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
370,Louisiana,Ascension,2012,359,309,46,4,0,0,0,122,61,37,0,19,340,0,0,0
371,Louisiana,Bossier,2012,365,268,93,4,0,0,0,140,64,41,0,0,227,0,136,2
372,Louisiana,Caddo,2012,363,255,103,4,1,0,0,176,67,42,0,0,285,0,78,0
373,Louisiana,Calcasieu,2012,366,260,100,6,0,0,0,136,64,42,0,0,203,16,147,0
374,Louisiana,East Baton Rouge,2012,363,204,148,9,2,0,0,151,77,47,0,9,171,4,176,3
375,Louisiana,Iberville,2012,363,286,64,13,0,0,0,122,67,39,0,5,303,0,55,0
376,Louisiana,Jefferson,2012,360,268,87,5,0,0,0,129,64,42,0,14,230,0,116,0
377,Louisiana,Lafayette,2012,366,229,134,3,0,0,0,129,67,45,0,0,168,0,196,2
378,Louisiana,Lafourche,2012,359,282,73,4,0,0,0,133,65,39,0,0,279,0,80,0
379,Louisiana,Livingston,2012,361,279,77,5,0,0,0,133,67,41,0,1,301,0,59,0
380,Louisiana,Orleans,2012,358,251,104,3,0,0,0,112,64,42,0,0,165,0,191,2
381,Louisiana,Ouachita,2012,366,173,193,0,0,0,0,91,65,51,0,0,44,0,322,0
382,Louisiana,Pointe Coupee,2012,361,281,71,9,0,0,0,150,77,41,0,0,361,0,0,0
383,Louisiana,Rapides,2012,362,177,185,0,0,0,0,88,66,52,0,0,0,0,362,0
384,Louisiana,St. Bernard,2012,359,146,176,30,7,0,0,174,102,54,0,0,122,94,142,1
385,Louisiana,St. Charles,2012,347,308,38,1,0,0,0,119,54,36,0,0,347,0,0,0
386,Louisiana,St. James,2012,365,340,23,2,0,0,0,122,47,33,0,0,365,0,0,0
387,Louisiana,St. John the Baptist,2012,359,284,65,10,0,0,0,129,67,40,0,0,359,0,0,0
388,Louisiana,St. Tammany,2012,359,267,89,3,0,0,0,122,64,41,0,0,254,0,105,0
389,Louisiana,Tangipahoa,2012,114,94,20,0,0,0,0,74,54,34,0,0,0,0,114,0
390,Louisiana,Terrebonne,2012,118,101,17,0,0,0,0,68,53,28,0,0,0,0,118,0
391,Louisiana,West Baton Rouge,2012,366,218,146,1,1,0,0,159,67,47,0,4,95,5,262,0

In [21]:
justin_df.Name

0                 Ouachita Parish, Louisiana
1                  Rapides Parish, Louisiana
2               St. Landry Parish, Louisiana
3              St. Tammany Parish, Louisiana
4               Tangipahoa Parish, Louisiana
5               Terrebonne Parish, Louisiana
6                 Androscoggin County, Maine
7                    Aroostook County, Maine
8                   Cumberland County, Maine
9                     Kennebec County, Maine
10                   Penobscot County, Maine
11                        York County, Maine
12                 Allegany County, Maryland
13             Anne Arundel County, Maryland
14                Baltimore County, Maryland
15                  Calvert County, Maryland
16                  Carroll County, Maryland
17                    Cecil County, Maryland
18                  Charles County, Maryland
19                Frederick County, Maryland
20                  Harford County, Maryland
21                   Howard County, Maryland
22               Montgomery County, Maryland
23          Prince George's County, Maryland
24               St. Mary's County, Maryland
25               Washington County, Maryland
26                 Wicomico County, Maryland
27                  Baltimore city, Maryland
28          Barnstable County, Massachusetts
29           Berkshire County, Massachusetts
                        ...
4949               Kenosha County, Wisconsin
4950             La Crosse County, Wisconsin
4951             Manitowoc County, Wisconsin
4952              Marathon County, Wisconsin
4953             Milwaukee County, Wisconsin
4954             Outagamie County, Wisconsin
4955               Ozaukee County, Wisconsin
4956               Portage County, Wisconsin
4957                Racine County, Wisconsin
4958                  Rock County, Wisconsin
4959             St. Croix County, Wisconsin
4960             Sheboygan County, Wisconsin
4961              Walworth County, Wisconsin
4962            Washington County, Wisconsin
4963              Waukesha County, Wisconsin
4964             Winnebago County, Wisconsin
4965                  Wood County, Wisconsin
4966                 Laramie County, Wyoming
4967                 Natrona County, Wyoming
4968          Arecibo Municipio, Puerto Rico
4969          Bayam?n Municipio, Puerto Rico
4970           Caguas Municipio, Puerto Rico
4971         Carolina Municipio, Puerto Rico
4972         Guaynabo Municipio, Puerto Rico
4973         Mayag?ez Municipio, Puerto Rico
4974            Ponce Municipio, Puerto Rico
4975         San Juan Municipio, Puerto Rico
4976         Toa Alta Municipio, Puerto Rico
4977         Toa Baja Municipio, Puerto Rico
4978    Trujillo Alto Municipio, Puerto Rico
Name: Name, Length: 4979, dtype: object

In [25]:
(aqi_2012_df.State.unique())

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Country Of Mexico', 'Delaware',
       'District Of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
       'Virgin Islands', 'Virginia', 'Washington', 'West Virginia',
       'Wisconsin', 'Wyoming'], dtype=object)

In [31]:
justin_df[justin_df['Name'].str.contains("Parish")] # which names contain 'Parish'

,Name,Total Population,Poverty Determinable,Below Poverty Level (PL),% Below PL,Poverty Status of Families,% of Families Below PL,Selected Characteristics,<50% Poverty Level,State Code,County Code,Year
0,"Ouachita Parish, Louisiana",155363,146095,35443,24.3,37910,20.0,NaN,NaN,22,73,2012
1,"Rapides Parish, Louisiana",132373,128128,28867,22.5,33286,17.2,NaN,NaN,22,79,2012
2,"St. Landry Parish, Louisiana",83662,82325,21149,25.7,21943,21.0,NaN,NaN,22,97,2012
3,"St. Tammany Parish, Louisiana",239453,237342,32212,13.6,65316,10.2,NaN,NaN,22,103,2012
4,"Tangipahoa Parish, Louisiana",123441,119480,29110,24.4,27469,18.9,NaN,NaN,22,105,2012
5,"Terrebonne Parish, Louisiana",111893,110088,20330,18.5,27860,12.7,NaN,NaN,22,109,2012
704,"Ascension Parish, Louisiana",112286,111087,13116,11.8,29123,10.3,NaN,NaN,22,5,2012
705,"Bossier Parish, Louisiana",122197,120261,15512,12.9,31360,11.7,NaN,NaN,22,15,2012
706,"Caddo Parish, Louisiana",257093,251810,49358,19.6,62845,15.5,NaN,NaN,22,17,2012
707,"Calcasieu Parish, Louisiana",194493,190579,31919,16.7,51530,13.6,NaN,NaN,22,19,2012
708,"East Baton Rouge Parish, Louisiana",444526,434269,88551,20.4,100032,14.0,NaN,NaN,22,33,2012
709,"Iberia Parish, Louisiana",73999,72804,14840,20.4,19250,18.7,NaN,NaN,22,45,2012
710,"Jefferson Parish, Louisiana",433676,430002,68210,15.9,104146,12.0,NaN,NaN,22,51,2012
711,"Lafayette Parish, Louisiana",227055,222231,39565,17.8,55558,14.2,NaN,NaN,22,55,2012
712,"Lafourche Parish, Louisiana",97029,95065,12517,13.2,25220,9.6,NaN,NaN,22,57,2012
713,"Livingston Parish, Louisiana",131942,129222,22916,17.7,34444,13.8,NaN,NaN,22,63,2012
714,"Orleans Parish, Louisiana",369250,357661,102724,28.7,76120,23.0,NaN,NaN,22,71,2012
1486,"Ascension Parish, Louisiana",114393,113503,11587,10.2,32778,8.9,NaN,NaN,22,5,2013
1487,"Bossier Parish, Louisiana",123823,120949,18075,14.9,31124,12.8,NaN,NaN,22,15,2013
1488,"Caddo Parish, Louisiana",254887,250334,54182,21.6,60198,16.6,NaN,NaN,22,17,2013
1489,"Calcasieu Parish, Louisiana",195296,191677,30420,15.9,50374,12.1,NaN,NaN,22,19,2013
1490,"East Baton Rouge Parish, Louisiana",445227,435808,90861,20.8,102999,14.3,NaN,NaN,22,33,2013
1491,"Iberia Parish, Louisiana",73878,72513,12633,17.4,18291,12.5,NaN,NaN,22,45,2013
1492,"Jefferson Parish, Louisiana",434767,431545,82608,19.1,104121,14.6,NaN,NaN,22,51,2013
1493,"Lafayette Parish, Louisiana",230845,225879,34679,15.4,56623,12.2,NaN,NaN,22,55,2013
1494,"Lafourche Parish, Louisiana",97141,94355,15780,16.7,24494,10.8,NaN,NaN,22,57,2013
1495,"Livingston Parish, Louisiana",134053,132828,21487,16.2,34552,12.0,NaN,NaN,22,63,2013
1496,"Orleans Parish, Louisiana",378715,367572,97970,26.7,79743,22.9,NaN,NaN,22,71,2013
1497,"Ouachita Parish, Louisiana",156220,146936,36198,24.6,38410,20.2,NaN,NaN,22,73,2013
1498,"Rapides Parish, Louisiana",132723,129489,24770,19.1,30079,14.0,NaN,NaN,22,79,2013
...,...,...,...,...,...,...,...,...,...,...,...,...
3590,"East Baton Rouge Parish, Louisiana",447037,436889,86232,19.7,97684,13.5,NaN,NaN,22,33,2016
3591,"Iberia Parish, Louisiana",73273,71607,16982,23.7,19211,21.9,NaN,NaN,22,45,2016
3592,"Jefferson Parish, Louisiana",436523,432415,67693,15.7,106145,12.6,NaN,NaN,22,51,2016
3593,"Lafayette Parish, Louisiana",241398,234994,45278,19.3,55317,13.1,NaN,NaN,22,55,2016
3594,"Lafourche Parish, Louisiana",98305,94725,17167,18.1,24601,13.8,NaN,NaN,22,57,2016
3595,"Livingston Parish, Louisiana",140138,138609,18467,13.3,34106,11.5,NaN,NaN,22,63,2016
3596,"Orleans Parish, Louisiana",391495,375903,88916,23.7,75729,17.1,NaN,NaN,22,71,2016
3597,"Ouachita Parish, Louisiana",156983,151613,37704,24.9,35009,19.9,NaN,NaN,22,73,2016
3598,"Rapides Parish, Louisiana",132424,128616,25096,19.5,32425,15.4,NaN,NaN,22,79,2016
3599,"St. Landry Parish, Louisiana",83883,82335,22384,27.2,20724,23.5,NaN,NaN,22,97,2016
3600,"St. Tammany Parish, Louisiana",253602,250658,21281,8.5,64876,6.0,NaN,NaN,22,103,2016
3601,"Tangipahoa Parish, Louisiana",130710,127260,25960,20.4,33369,16.9,NaN,NaN,22,105,2016
3602,"Terrebonne Parish, Louisiana",113220,111735,26021,23.3,27840,18.7,NaN,NaN,22,109,2016
4859,"Ascension Parish, Louisiana",122948,121895,18018,14.8,31361,11.1,NaN,NaN,22,5,2017
4860,"Bossier Parish, Louisiana",127634,124325,24219,19.5,34030,15.6,NaN,NaN,22,15,2017
4861,"Caddo Parish, Louisiana",246581,241396,64507,26.7,57253,20.9,NaN,NaN,22,17,2017
4862,"Calcasieu Parish, Louisiana",202445,199105,26071,13.1,49540,9.6,NaN,NaN,22,19,2017
4863,"East Baton Rouge Parish, Louisiana",446268,437794,82173,18.8,98936,12.4,NaN,NaN,22,33,2017
4864,"Iberia Parish, Louisiana",72176,71018,17289,24.3,16373,22.5,NaN,NaN,22,45,2017
4865,"Jefferson Parish, Louisiana",439036,435457,74634,17.1,107507,13.8,NaN,NaN,22,51,2017
4866,"Lafayette Parish, Louisiana",242485,237467,43839,18.5,55714,13.5,NaN,NaN,22,55,2017
4867,"Lafourche Parish, Louisiana",98426,96222,14836,15.4,26174,11.7,NaN,NaN,22,57,2017
4868,"Livingston Parish, Louisiana",138228,137262,14664,10.7,37428,8.8,NaN,NaN,22,63,2017
4869,"Orleans Parish, Louisiana",393292,380032,99735,26.2,72333,18.9,NaN,NaN,22,71,2017
4870,"Ouachita Parish, Louisiana",155874,148717,39028,26.2,38259,21.4,NaN,NaN,22,73,2017
4871,"Rapides Parish, Louisiana",131648,127584,25537,20.0,31441,15.9,NaN,NaN,22,79,2017
4872,"St. Landry Parish, Louisiana",83497,81528,21454,26.3,19404,21.4,NaN,NaN,22,97,2017
4873,"St. Tammany Parish, Louisiana",256327,254083,29001,11.4,65672,8.1,NaN,NaN,22,103,2017
4874,"Tangipahoa Parish, Louisiana",132497,127789,26502,20.7,32719,15.5,NaN,NaN,22,105,2017
4875,"Terrebonne Parish, Louisiana",112086,110249,22284,20.2,26597,16.0,NaN,NaN,22,109,2017

In [32]:
def join_county_state (county, state):
    if state == 'Louisiana':
        name = f"{county} Parish, {state}"
    else:
        name = f"{county} County, {state}"
    return name

In [34]:

#import os

def read_all_epa_years ():
    
    df2012 = pd.read_csv('Copy of annual_aqi_by_county_2012.csv')
    df2013 = pd.read_csv('Copy of annual_aqi_by_county_2013.csv')
    df2014 = pd.read_csv('Copy of annual_aqi_by_county_2014.csv')
    df2015 = pd.read_csv('Copy of annual_aqi_by_county_2015.csv')
    df2016 = pd.read_csv('Copy of annual_aqi_by_county_2016.csv')
    df2017 = pd.read_csv('Copy of annual_aqi_by_county_2017.csv')
    all_years_df = pd.concat([df2012, df2013, df2014, df2015, df2016, df2017], ignore_index=True)
    
    return all_years_df

all_years_df = read_all_epa_years()

In [35]:
all_years_df.shape

(6363, 19)

In [ ]:
all_years_df.to_csv(""